/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author LENOVO
 */
public class PenampilGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PenampilGambarButton
     */
    public PenampilGambarButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlButton = new javax.swing.JPanel();
        BtnGS = new javax.swing.JButton();
        BtnJvE = new javax.swing.JButton();
        BtnPSQL = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        PnlImage = new javax.swing.JPanel();
        LblGs = new javax.swing.JLabel();
        LblJVE = new javax.swing.JLabel();
        LblPSQL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnGS.setText("GlassFish");
        BtnGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGSActionPerformed(evt);
            }
        });
        PnlButton.add(BtnGS);

        BtnJvE.setText("JavaEE");
        BtnJvE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJvEActionPerformed(evt);
            }
        });
        PnlButton.add(BtnJvE);

        BtnPSQL.setText("PostgreSQL");
        BtnPSQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPSQLActionPerformed(evt);
            }
        });
        PnlButton.add(BtnPSQL);

        BtnExit.setText("Exit");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        PnlButton.add(BtnExit);

        getContentPane().add(PnlButton, java.awt.BorderLayout.PAGE_START);

        PnlImage.setLayout(new java.awt.CardLayout());

        LblGs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/GlassFish (1).jpg"))); // NOI18N
        PnlImage.add(LblGs, "0");

        LblJVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Begining Java (1).jpg"))); // NOI18N
        PnlImage.add(LblJVE, "1");

        LblPSQL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Postgresql (1).jpg"))); // NOI18N
        PnlImage.add(LblPSQL, "2");

        getContentPane().add(PnlImage, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGSActionPerformed
        CardLayout cl =(CardLayout)(PnlImage.getLayout());
        cl.show(PnlImage,"0");
    }//GEN-LAST:event_BtnGSActionPerformed

    private void BtnJvEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJvEActionPerformed
                CardLayout cl =(CardLayout)(PnlImage.getLayout());
        cl.show(PnlImage,"1");
    }//GEN-LAST:event_BtnJvEActionPerformed

    private void BtnPSQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPSQLActionPerformed
                CardLayout cl =(CardLayout)(PnlImage.getLayout());
        cl.show(PnlImage,"2");
    }//GEN-LAST:event_BtnPSQLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnGS;
    private javax.swing.JButton BtnJvE;
    private javax.swing.JButton BtnPSQL;
    private javax.swing.JLabel LblGs;
    private javax.swing.JLabel LblJVE;
    private javax.swing.JLabel LblPSQL;
    private javax.swing.JPanel PnlButton;
    private javax.swing.JPanel PnlImage;
    // End of variables declaration//GEN-END:variables
}
